# Game theory using Nashpy

## Prisioner's Dilemma

1) Install Nashpy

2) Import the necessary Python modules/packages

In [6]:
import nashpy as nash
import numpy as np

3) Create the payoff Matrix that model our problem

In [35]:
Alan = np.array([[-1, -15], [0, -10]])
Ben = np.array([[-1, 0], [-15, -10]])

#Reverse silent and confession
Alan2 = np.array([[0, -10], [-15, -1]])
Ben2 = np.array([[-10, -15], [0, -1]])

4) Create the game using the matrix created

In [36]:
game1 = nash.Game(Alan, Ben)
game1


Bi matrix game with payoff matrices:

Row player:
[[ -1 -15]
 [  0 -10]]

Column player:
[[ -1   0]
 [-15 -10]]

In [37]:

game2 = nash.Game(Alan2, Ben2)
game2

Bi matrix game with payoff matrices:

Row player:
[[  0 -10]
 [-15  -1]]

Column player:
[[-10 -15]
 [  0  -1]]

5) Find the Nash Equilibrium with Support Enumeration

In [44]:
equilibria = game1.support_enumeration()
for eq in equilibria:
    print(eq)

(array([0., 1.]), array([0., 1.]))


In [45]:
equilibria2 = game2.support_enumeration()
for eq in equilibria2:
    print(eq)

(array([1., 0.]), array([1., 0.]))


## Game 2

Given the following payoff matrix decide which are the strategies both players should choose in order to reach the Nash Equilibrium.Provide also the output analysis.

![Game 2 payoff matrix](game2.PNG)

In [46]:
#Payoff matrix
PlayerA = np.array([[2, 0,], [4, 2]])
PlayerB = np.array([[4, 2], [2, 0]])

In [47]:
#Create game
game3 = nash.Game(PlayerA, PlayerB)
game3

Bi matrix game with payoff matrices:

Row player:
[[2 0]
 [4 2]]

Column player:
[[4 2]
 [2 0]]

In [48]:
#Find Nash Equilibrium
equilibria3 = game3.support_enumeration()
for eq in equilibria3:
    print(eq)

(array([0., 1.]), array([1., 0.]))


In [ ]:
#Nash equilibrium achieved if PlayerA goes Bottom and PlayerB chooses Left. 
